In [1]:
import h5py as hdf
import numpy as np

# Experimentations in Numpy

In [2]:
temparature = np.random.random(1024)

In [4]:
temparature

array([0.7267144 , 0.85711598, 0.36514943, ..., 0.85686586, 0.58933917,
       0.76831601])

In [5]:
dt = 10.0
start_time = 1375204299
station = 15

### store into numpy file using savez

In [7]:
np.savez("weather.npz",data=temparature,interval=dt,time=start_time)

### load numpy file

In [8]:
out = np.load("weather.npz")

In [9]:
out['data']

array([0.7267144 , 0.85711598, 0.36514943, ..., 0.85686586, 0.58933917,
       0.76831601])

In [10]:
out['interval']

array(10.)

In [11]:
out['time']

array(1375204299)

# Experiments with HDF5 file

In [13]:
import h5py as hdf

In [15]:
f = hdf.File("weather.hdf5","w-")

In [16]:
f["/15/temperature"] = temparature
f["/15/temperature"].attrs["interval"] = 10.0
f["/15/temperature"].attrs["start_time"] = 1375204299
f["/15/wind"] = np.random.random(2048)
f['/15/wind'].attrs["interval"] = 5.0

In [17]:
f.close()

In [18]:
g = hdf.File("weather.hdf5","r")

In [19]:
g["/15/wind"]

<HDF5 dataset "wind": shape (2048,), type "<f8">

In [22]:
dataset = g["/15/temperature"]

In [23]:
dataset.attrs

<Attributes of HDF5 object at 1895815324248>

In [24]:
for i in dataset.attrs:
    print(i)

interval
start_time


In [27]:
for i,j in dataset.attrs.items():
    print(i,j)

interval 10.0
start_time 1375204299


### print all values of "/15/temperature" aka g

In [28]:
dataset[:]

array([0.7267144 , 0.85711598, 0.36514943, ..., 0.85686586, 0.58933917,
       0.76831601])

In [29]:
dataset[:5]

array([0.7267144 , 0.85711598, 0.36514943, 0.19349486, 0.87321003])

In [30]:
dataset[:10]

array([0.7267144 , 0.85711598, 0.36514943, 0.19349486, 0.87321003,
       0.11105231, 0.36707629, 0.59315507, 0.76308226, 0.20563836])

In [32]:
dataset[1:10:2]

array([0.85711598, 0.19349486, 0.11105231, 0.59315507, 0.20563836])

In [33]:
dataset[:10:2]

array([0.7267144 , 0.36514943, 0.87321003, 0.36707629, 0.76308226])